[2024-10-30T03:49:55.907+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-30T03:49:55.914+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-10-29T00:00:00+00:00 [queued]>
[2024-10-30T03:49:55.917+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: my_dag.inaccurate scheduled__2024-10-29T00:00:00+00:00 [queued]>
[2024-10-30T03:49:55.917+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-10-30T03:49:55.921+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): inaccurate> on 2024-10-29 00:00:00+00:00
[2024-10-30T03:49:55.923+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=127) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-30T03:49:55.924+0000] {standard_task_runner.py:72} INFO - Started process 129 to run task
[2024-10-30T03:49:55.925+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'my_dag', 'inaccurate', 'scheduled__2024-10-29T00:00:00+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmp3ob3z_j8']
[2024-10-30T03:49:55.925+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask inaccurate
[2024-10-30T03:49:55.942+0000] {task_command.py:467} INFO - Running <TaskInstance: my_dag.inaccurate scheduled__2024-10-29T00:00:00+00:00 [running]> on host 0966d11159e9
[2024-10-30T03:49:55.965+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='my_dag' AIRFLOW_CTX_TASK_ID='inaccurate' AIRFLOW_CTX_EXECUTION_DATE='2024-10-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-29T00:00:00+00:00'
[2024-10-30T03:49:55.965+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2024-10-30T03:49:55.965+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2024-10-30T03:49:55.966+0000] {logging_mixin.py:190} INFO - Current task name:inaccurate state:running start_date:2024-10-30 03:49:55.914548+00:00
[2024-10-30T03:49:55.966+0000] {logging_mixin.py:190} INFO - Dag name:my_dag and current dag run status:running
[2024-10-30T03:49:55.966+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-30T03:49:55.966+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-10-30T03:49:55.966+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', "echo 'inaccurate'"]
[2024-10-30T03:49:55.970+0000] {subprocess.py:86} INFO - Output:
[2024-10-30T03:49:55.971+0000] {subprocess.py:93} INFO - inaccurate
[2024-10-30T03:49:55.971+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-10-30T03:49:55.980+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-30T03:49:55.980+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=my_dag, task_id=inaccurate, run_id=scheduled__2024-10-29T00:00:00+00:00, execution_date=20241029T000000, start_date=20241030T034955, end_date=20241030T034955
[2024-10-30T03:49:55.983+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2024-10-30T03:49:55.983+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2024-10-30T03:49:55.983+0000] {logging_mixin.py:190} INFO - Dag name:my_dag queued_at:2024-10-30 03:49:52.378728+00:00
[2024-10-30T03:49:55.983+0000] {logging_mixin.py:190} INFO - Task hostname:0966d11159e9 operator:BashOperator
[2024-10-30T03:49:56.025+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-30T03:49:56.033+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-30T03:49:56.033+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
